### ISSUE TITLE
The library no longer works

### ISSUE THREAD

**Issue by joao-fm-santos** [waigel/node-ms-teams-webhook#7]
When trying to execute the demo example, no message is sent via the webhook. 
However, if I take the same request and execute it with curl, it does get executed.

Could you please help?

**Comment by blumendorf** [comment]
Teams seems to no longer accept string-based messages since 2 days ago. 
If you send the JSON Object directly it works, but the type of the `send` method needs to be changed.

**Comment by waigel** [comment]
Yeah, you are correct. It looks like Microsoft had a breaking change in the webhook API. So I release an update that use `JSON object` directly instead of an `JSON string`. It is a breaking change, so you need to adjust your code. Sorry for interruptions.
